packages:
  - "packages/*"
  - "apps/trading-platform/frontend"
  - "apps/trading-platform/api-gateway"
  - "apps/trading-platform/data-collector"
  - "apps/trading-platform/job-processor"
  - "apps/trading-platform/analysis-engine"
  - "apps/trading-platform/background-agent"
