version: '3.8'

services:
  searxng:
    image: searxng/searxng:latest
    container_name: yobi-searxng
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
      - ./data:/var/lib/searxng/data:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY:-change_me_searxng_secret}
      - SEARXNG_REDIS_URL=redis://redis:6379/0
    networks:
      - searxng
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: yobi-searxng-redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - searxng
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Nginx proxy for better performance and HTTPS
  nginx:
    image: nginx:alpine
    container_name: yobi-searxng-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - searxng
    depends_on:
      - searxng
    profiles:
      - nginx

networks:
  searxng:
    driver: bridge

volumes:
  redis-data:
    driver: local 