version: '3.8'

services:
  # Database Services
  postgres:
    image: postgres:15
    container_name: yobi-postgres
    environment:
      POSTGRES_DB: yobi
      POSTGRES_USER: yobi
      POSTGRES_PASSWORD: ${DB_PASSWORD:-yobi123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - yobi-network

  redis:
    image: redis:7-alpine
    container_name: yobi-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - yobi-network

  mongodb:
    image: mongo:7
    container_name: yobi-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: yobi
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-yobi123}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - yobi-network

  # Application Services
  api-gateway:
    build: ./api-gateway
    container_name: yobi-api-gateway
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://yobi:${DB_PASSWORD:-yobi123}@postgres:5432/yobi
      - REDIS_URL=redis://redis:6379
      - DATA_COLLECTOR_URL=http://data-collector:3004
      - BACKGROUND_AGENT_URL=http://background-agent:3008
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - redis
      - data-collector
      - background-agent
    networks:
      - yobi-network

  data-collector:
    build: ./data-collector
    container_name: yobi-data-collector
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://yobi:${DB_PASSWORD:-yobi123}@postgres:5432/yobi
      - REDIS_URL=redis://redis:6379
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
    ports:
      - "3004:3004"
    depends_on:
      - postgres
      - redis
    networks:
      - yobi-network

  background-agent:
    build: ./background-agent
    container_name: yobi-background-agent
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://yobi:${DB_PASSWORD:-yobi123}@postgres:5432/yobi
      - REDIS_URL=redis://redis:6379
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
      - SERP_API_KEY=${SERP_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - DATA_COLLECTOR_URL=http://data-collector:3004
      - API_GATEWAY_URL=http://api-gateway:3002
    ports:
      - "3008:3008"
    depends_on:
      - postgres
      - redis
      - mongodb
    networks:
      - yobi-network

  frontend:
    build: ./frontend
    container_name: yobi-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3002
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - yobi-network

volumes:
  postgres_data:
  redis_data:
  mongodb_data:

networks:
  yobi-network:
    driver: bridge 