version: '3.8'

services:
  api-gateway:
    build:
      context: ../..
      dockerfile: apps/trading-platform/api-gateway/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DATABASE_URL=${NEON_DATABASE_URL}
      - MONGODB_URI=${MONGODB_URI}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - analysis-engine
      - data-collector
    restart: unless-stopped
    networks:
      - trading-network

  analysis-engine:
    build:
      context: ../..
      dockerfile: apps/trading-platform/analysis-engine/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=3003
      - DATABASE_URL=${NEON_DATABASE_URL}
      - MONGODB_URI=${MONGODB_URI}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - YAHOO_FINANCE_API_KEY=${YAHOO_FINANCE_API_KEY}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
    restart: unless-stopped
    networks:
      - trading-network

  data-collector:
    build:
      context: ../..
      dockerfile: apps/trading-platform/data-collector/Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
      - DATABASE_URL=${NEON_DATABASE_URL}
      - MONGODB_URI=${MONGODB_URI}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - YAHOO_FINANCE_API_KEY=${YAHOO_FINANCE_API_KEY}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - IEX_CLOUD_API_KEY=${IEX_CLOUD_API_KEY}
    restart: unless-stopped
    networks:
      - trading-network

  job-processor:
    build:
      context: ../..
      dockerfile: apps/trading-platform/job-processor/Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${NEON_DATABASE_URL}
      - MONGODB_URI=${MONGODB_URI}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
    restart: unless-stopped
    networks:
      - trading-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api-gateway
    restart: unless-stopped
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge 